[helpers]

[default]
depends = []

[default.files]
gitconfig = "~/.gitconfig"
bashrc = "~/.bashrc"
"bin/review.sh" = "~/bin/review.sh"
"bin/commit.sh" = "~/bin/commit.sh"
"bin/liga.sh" = "~/bin/liga.sh"
"bin/notify.sh" = "~/bin/notify.sh"
"bin/nvim-doc.sh" = "~/bin/nvim-doc.sh"
"bin/zellij-pane.sh" = "~/bin/zellij-pane.sh"
"config/alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"config/btop/btop.conf" = "~/.config/btop/btop.conf"
"config/git/ignore" = "~/.config/git/ignore"
"config/karabiner/karabiner.json" = "~/.config/karabiner/karabiner.json"
"config/moxide/settings.toml" = "~/.config/moxide/settings.toml"
"config/nvim/colors" = "~/.config/nvim/colors"
"config/nvim/compiler" = "~/.config/nvim/compiler"
"config/nvim/ftplugin" = "~/.config/nvim/ftplugin"
"config/nvim/init.lua" = "~/.config/nvim/init.lua"
"config/nvim/luarc.json" = "~/.config/nvim/.luarc.json"
"config/nvim/lua" = "~/.config/nvim/lua"
"config/rumdl/rumdl.toml" = "~/.config/rumdl/rumdl.toml"
"config/zellij/config.kdl" = "~/.config/zellij/config.kdl"
"config/zellij/layouts/hacking.kdl" = "~/.config/zellij/layouts/hacking.kdl"
"config/claude/settings.json" = "~/.claude/settings.json"
"config/claude/CLAUDE.md" = "~/.claude/CLAUDE.md"
"config/claude/CLAUDE.md" = "~/.codex/AGENTS.md"
"config/codex/config.toml" = "~/.codex/config.toml"

[default.variables]
font_size = 12.0

[settings]
default_target_type = "automatic"
